[project]
name = "stocks-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dependency-injector>=4.46.0",
    "fastapi[standard]>=0.115.12",
    "pyhumps>=3.8.0",
    "supabase>=2.15.1",
]
